[project]
name = "japanese-wikipedia-rag"
version = "0.1.0"
description = "RAG pipeline for querying Japanese wikipedia with English"
authors = [
    {name = "Matt Luettgen",email = "mrluettgen@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "wikipedia-api (>=0.14.1,<0.15.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "tdqm (>=0.0.1,<0.0.2)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
