[tool.poetry]
name = "notebooks"
version = "0.1.0"
description = ""
authors = ["Matt Luettgen <mrluettgen@gmail.com>"]
package-mode=false

[tool.poetry.dependencies]
python = "<3.14,>=3.10"
    pinecone = ">=9.0.0,<10.0.0"
    voyageai = ">=0.3.7,<0.4.0"
ipykernel = "^7.2.0"
dotenv = "^0.9.9"
openai = "^2.36.0"
pinecone-text = "^0.11.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

